menu:
    home: /
    blog: /archives/
    rss: /atom.xml
    mypage: http://www.zhomeplus.com/mypage_cn.html

favicon: /favicon.png

google_analytics: 
baidu_analytics: //hm.baidu.com/hm.js?9e955db40541639352977e826bf05a11

selfIntro:
    title: 风中陀螺
    content: 当你没有借口的那一刻，就是你成功的开始。
    social:
        zhomeplus: http://www.zhomeplus.com/
        weibo: http://weibo.com/cldesign